name: parentpod_stud
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  http: ^0.13.6
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  get_storage: ^2.1.1
  intl: ^0.18.1
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.7+5
  dio: ^5.1.2
  simple_gesture_detector: ^0.2.0
  cached_network_image: ^3.2.3
  html: ^0.15.3
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  upgrader: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf



  #         - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
